apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: deployment-weather-backend
  namespace: greetings-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: greetings-app
    subApp: greetings-channel
spec:
  template:
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: weather-backend
    spec:
      selector:
        matchLabels:
          app: greetings-app
          subApp: greetings-channel
          comp: weather-backend
      replicas: 1
      template:
        metadata:
          labels:
            app: greetings-app
            subApp: greetings-channel
            comp: weather-backend
        spec:
          containers:
            - name: my-container
              image: gandhicloud/weather-backend-icam
              imagePullPolicy: Always
              ports:
                - containerPort: 9094
              env:
                - name: response.delay.seconds
                  value: "2"
                - name: IBM_APM_RUM_ENABLED
                  value: "true" 
                - name: OPENTRACING_ENABLED
                  value: "true"      
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "200m"
                limits:
                  memory: "512Mi"
                  cpu: "400m"
          volumeMounts:
            - name: global-environment
              mountPath: /opt/ibm/apm/serverconfig
          volumes:
            - name: global-environment
              secret:
                secretName: icam-server-secret
                optional: true
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  name: service-weather-backend
  namespace: greetings-channel-ns
  annotations:
    app.ibm.com/is-local-deployable: "false"
  labels:
    app: greetings-app
    subApp: greetings-channel
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: weather-backend
      labels:
        app: greetings-app
        subApp: greetings-channel        
        comp: weather-backend
    spec:
      type: NodePort
      ports:
        - name: my-http
          port: 9094
          nodePort: 32424
      selector:
        app: greetings-app
        subApp: greetings-channel
        comp: weather-backend
