kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lwdc-rolebinding-greetings
  namespace: greetings-app-ns
subjects:
- kind: User
  name: system:serviceaccount:greetings-app-ns:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lwdc-query
  apiGroup: rbac.authorization.k8s.io
